### ISSUE TITLE
Probably a brazen and daring request for help

### ISSUE THREAD

**Issue by ThisisHappyEL** [el-falso/gdlinter#3]
I really wanted to start my journey to Godot “right”, and therefore I immediately thought about a linter. The installation was successful (sort of). If you run the linting command from a third-party code editor (vs code), the result is working, but, unfortunately, the gdlint window says that the path to gdlint was not found.

I was looking for a solution to this problem, but it feels like I'm the only one who encountered this

**Comment by plink-plonk-will** [comment]
You're welcome! Thank you for releasing a new version :D
