### ISSUE TITLE
Can't find gdlint

### ISSUE THREAD

**Issue by eldyer** [el-falso/gdlinter#7]
The problem happens with 2.0.0 from the AssetLib but also with current master.

Version 1.0.1 still works.

I'm using Godot 4.3.dev5.

**Comment by el-falso** [comment]
Thank you for reporting, it's a known issue and someone has also a fix for it in https://github.com/el-falso/gdlinter/issues/4#issuecomment-2011405458. I'll push out the fix when I'm on the PC again.

**Comment by eldyer** [comment]
I'm on linux and still get the error with 2.0.1. I'll see if I can find out where the problem is.

**Comment by eldyer** [comment]
So the problem seems to be in `get_gdlint_path`.
In my case it returns `~/.local/bin/gdlint`, but it's not there, it's at `/usr/bin/gdlint` in my case. Returning just `"gdlint"` as for windows works for me.

**Comment by el-falso** [comment]
Thank you for reproducing the issue. Seems like it's more difficult to get the path to gdlint for various operating systems and for various different installations than I thought.

Hope #10 fixes it this time, since I added two fallbacks.

**Comment by eldyer** [comment]
:+1: it's working now.

Thanks for creating this awesome plugin!

**Comment by el-falso** [comment]
Great, thank you really much for your kind words. ❤️

I really hope this issue will be fixed forever now, since I'm really out of solutions. 😅
